# Generated by Django 4.0.5 on 2022-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('trek_name', models.CharField(max_length=100)),
                ('original_format', models.CharField(max_length=100)),
                ('original_tracks', models.CharField(max_length=100)),
                ('convertable_tracks', models.CharField(max_length=100)),
                ('convertable_format', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
