# Generated by Django 4.0.5 on 2022-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('original_tracks', models.CharField(max_length=100)),
                ('convertable_tracks', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
